function write3DHtml(outputHtml, scene)
%WRITE3DHTML Write the standalone 3D replay report.
%
%   ltsviz.write3DHtml(outputHtml, scene)
%
% Embeds the scene payload, the vendored three.js build (external/three),
% and the viewer application (+ltsviz/+assets) into a single HTML file that
% renders offline in any WebGL-capable browser.

outputHtml = char(outputHtml);
outputDir = fileparts(outputHtml);
if ~isempty(outputDir) && ~exist(outputDir, 'dir')
    mkdir(outputDir);
end

assetRoot = fullfile(fileparts(mfilename('fullpath')), '+assets');
css = fileread(fullfile(assetRoot, 'report3d.css'));
appJs = fileread(fullfile(assetRoot, 'app3d.js'));
threeTag = threeScriptTag();
payload = strrep(jsonencode(scene), '</', '<\/');

html = sprintf([ ...
    '<!doctype html>\n<html>\n<head>\n<meta charset="utf-8">\n' ...
    '<meta name="viewport" content="width=device-width, initial-scale=1">\n' ...
    '<title>LTS 3D Replay</title>\n<style>\n%s</style>\n</head>\n<body>\n' ...
    '<div id="app">\n' ...
    '<header id="topbar">\n' ...
    '  <div id="brand"><span class="dot"></span>' ...
    '<span class="name" id="title">LTS 3D Replay</span></div>\n' ...
    '  <div id="files"></div>\n' ...
    '  <div id="metricChips"></div>\n' ...
    '</header>\n' ...
    '<div id="main">\n' ...
    '  <canvas id="view"></canvas>\n' ...
    '  <div class="hud" id="cluster">\n' ...
    '    <div id="speedRow"><span id="speedVal">0</span>' ...
    '<span id="speedUnit">km/h</span></div>\n' ...
    '    <div class="gaugeLabel">Pedal</div>\n' ...
    '    <div class="barRow" id="throttleBar"><span class="tag">TH</span>' ...
    '<span class="barTrack"><span class="barFill" id="thFill"></span></span></div>\n' ...
    '    <div class="barRow" id="brakeBar"><span class="tag">BR</span>' ...
    '<span class="barTrack"><span class="barFill" id="brFill"></span></span></div>\n' ...
    '    <div class="gaugeLabel">Steering</div>\n' ...
    '    <svg id="steerGlyph" viewBox="0 0 64 64">' ...
    '<circle cx="32" cy="32" r="22" fill="none" stroke="#4f8cff" stroke-width="4"/>' ...
    '<circle cx="32" cy="32" r="5" fill="#4f8cff"/>' ...
    '<line x1="32" y1="10" x2="32" y2="27" stroke="#4f8cff" stroke-width="4"/>' ...
    '<line x1="12" y1="41" x2="27" y2="36" stroke="#4f8cff" stroke-width="4"/>' ...
    '<line x1="52" y1="41" x2="37" y2="36" stroke="#4f8cff" stroke-width="4"/></svg>\n' ...
    '    <div id="deltaRow">\n' ...
    '      <div class="miniChip" id="deltaPathChip"><div class="v" id="deltaPathVal">—</div>' ...
    '<div class="k">&Delta;path m</div></div>\n' ...
    '      <div class="miniChip"><div class="v" id="latGVal">0.00</div>' ...
    '<div class="k">lat g</div></div>\n' ...
    '    </div>\n' ...
    '    <div class="toggles">\n' ...
    '      <label class="toggle"><input type="checkbox" id="tgSim" checked>' ...
    '<span class="swatch" style="background:#4f8cff"></span>Simulation car</label>\n' ...
    '      <label class="toggle"><input type="checkbox" id="tgReal" checked>' ...
    '<span class="swatch" style="background:#ff5964"></span>Reality car</label>\n' ...
    '      <label class="toggle"><input type="checkbox" id="tgTrail" checked>Trails</label>\n' ...
    '      <label class="toggle"><input type="checkbox" id="tgCones" checked>Cones</label>\n' ...
    '      <label class="toggle"><input type="checkbox" id="tgLabels" checked>Car labels</label>\n' ...
    '    </div>\n' ...
    '    <div id="noteAttitude">Body attitude estimated from accelerometer channels.</div>\n' ...
    '  </div>\n' ...
    '  <div class="hud" id="camBox">\n' ...
    '    <button class="ctrl" data-cam="orbit" title="Free orbit (drag, wheel, right-drag pan)">Orbit</button>\n' ...
    '    <button class="ctrl" data-cam="chase" title="Chase the simulation car">Chase</button>\n' ...
    '    <button class="ctrl" data-cam="cockpit" title="Driver eye view">Cockpit</button>\n' ...
    '    <button class="ctrl" data-cam="top" title="Overhead">Top</button>\n' ...
    '  </div>\n' ...
    '</div>\n' ...
    '<footer id="dock">\n' ...
    '  <div id="controls">\n' ...
    '    <button class="ctrl icon" id="playBtn" aria-label="Play">' ...
    '<svg id="playIconPlay" viewBox="0 0 16 16"><path d="M4 2l10 6-10 6z"/></svg>' ...
    '<svg id="playIconPause" viewBox="0 0 16 16" style="display:none"><path d="M3 2h4v12H3zM9 2h4v12H9z"/></svg></button>\n' ...
    '    <button class="ctrl icon" id="backBtn" title="Back 2 s (Left)">' ...
    '<svg viewBox="0 0 16 16"><path d="M3 2h2v12H3zM14 2v12L6 8z"/></svg></button>\n' ...
    '    <button class="ctrl icon" id="fwdBtn" title="Forward 2 s (Right)">' ...
    '<svg viewBox="0 0 16 16"><path d="M11 2h2v12h-2zM2 2l8 6-8 6z"/></svg></button>\n' ...
    '    <span id="timeNow">0:00.0</span><span id="timeTotal">/ 0:00.0</span>\n' ...
    '    <div id="scrubWrap"><input type="range" id="scrubber" min="0" max="1000" value="0" step="1"></div>\n' ...
    '    <div class="spacer"></div>\n' ...
    '    <span id="rateLabel">Speed</span>\n' ...
    '    <select class="ctrl" id="rateSel">' ...
    '<option value="0.25">0.25&times;</option><option value="0.5">0.5&times;</option>' ...
    '<option value="1" selected>1&times;</option><option value="2">2&times;</option>' ...
    '<option value="4">4&times;</option></select>\n' ...
    '    <div class="spacer"></div>\n' ...
    '    <button class="ctrl icon active" id="loopBtn" title="Loop (L)">' ...
    '<svg viewBox="0 0 24 24" style="fill:none;stroke:currentColor;stroke-width:2.4;stroke-linecap:round;stroke-linejoin:round">' ...
    '<path d="M17 2l4 4-4 4"/><path d="M3 12v-2a4 4 0 0 1 4-4h14"/>' ...
    '<path d="M7 22l-4-4 4-4"/><path d="M21 12v2a4 4 0 0 1-4 4H3"/></svg></button>\n' ...
    '    <button class="ctrl icon" id="helpBtn" title="Shortcuts (H or ?)">' ...
    '<svg viewBox="0 0 16 16"><path d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zm0 11.6a1.1 1.1 0 1 1 0-2.2 1.1 1.1 0 0 1 0 2.2zm1.9-5.3c-.6.5-.9.8-.9 1.5H7c0-1.3.5-1.9 1.2-2.5.5-.4.8-.7.8-1.2 0-.6-.5-1-1.2-1-.8 0-1.3.5-1.4 1.3H5C5.1 3.9 6.3 3 7.9 3c1.5 0 2.9.9 2.9 2.4 0 .8-.4 1.4-.9 1.9z"/></svg></button>\n' ...
    '  </div>\n' ...
    '  <div id="charts">\n' ...
    '    <div class="chartCard"><div class="chartTitle">Speed' ...
    '<span class="legend">sim<i style="background:#4f8cff"></i>real<i style="background:#ff5964"></i></span></div>' ...
    '<canvas class="chart" id="chartSpeed"></canvas></div>\n' ...
    '    <div class="chartCard"><div class="chartTitle">Pedal inputs (real dashed)' ...
    '<span class="legend">throttle<i style="background:#3fd68f"></i>brake<i style="background:#ff5964"></i></span></div>' ...
    '<canvas class="chart" id="chartInputs"></canvas></div>\n' ...
    '  </div>\n' ...
    '</footer>\n' ...
    '</div>\n' ...
    '<div class="overlay" id="loading"><div class="card"><div class="spin"></div>' ...
    'Building 3D scene&hellip;</div></div>\n' ...
    '<div class="overlay" id="help" hidden><div class="card">\n' ...
    '  <h2>Keyboard &amp; mouse</h2>\n' ...
    '  <div id="helpKeys">\n' ...
    '    <div><kbd>Space</kbd> play / pause</div>\n' ...
    '    <div><kbd>&larr;</kbd> / <kbd>&rarr;</kbd> seek &minus;/+ 2 s</div>\n' ...
    '    <div><kbd>Shift</kbd> + <kbd>&larr;</kbd>/<kbd>&rarr;</kbd> seek 10 s</div>\n' ...
    '    <div><kbd>&uarr;</kbd> / <kbd>&darr;</kbd> playback speed</div>\n' ...
    '    <div><kbd>C</kbd> cycle camera</div>\n' ...
    '    <div><kbd>R</kbd> restart lap</div>\n' ...
    '    <div><kbd>L</kbd> loop on/off</div>\n' ...
    '    <div><kbd>T</kbd> trails on/off</div>\n' ...
    '    <div>drag &mdash; orbit &middot; wheel &mdash; zoom</div>\n' ...
    '    <div>right-drag / <kbd>Shift</kbd>+drag &mdash; pan</div>\n' ...
    '    <div>click charts to scrub</div>\n' ...
    '  </div>\n' ...
    '  <p>The blue car replays the simulation; the red ghost is the aligned ' ...
    'real run. Body roll and pitch are visual estimates from accelerometer ' ...
    'channels, not measured suspension data.</p>\n' ...
    '  <button class="ctrl" id="helpClose">Close</button>\n' ...
    '</div></div>\n' ...
    '<div class="overlay" id="fatal" hidden><div class="card">\n' ...
    '  <h2>Cannot render this report</h2>\n' ...
    '  <p id="fatalMsg"></p>\n' ...
    '</div></div>\n' ...
    '<div id="toast"></div>\n' ...
    '<script>window.LTS_SCENE = %s;</script>\n' ...
    '%s\n' ...
    '<script>\n%s\n</script>\n' ...
    '</body>\n</html>\n'], ...
    css, payload, threeTag, appJs);

fid = fopen(outputHtml, 'w', 'n', 'UTF-8');
if fid < 0
    error('ltsviz:HtmlOpenFailed', 'Could not write %s.', outputHtml);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s', html);
end

function tag = threeScriptTag()
root = fileparts(fileparts(mfilename('fullpath')));
candidates = { ...
    fullfile(root, 'external', 'three', 'three.min.js'); ...
    fullfile(userHome(), '.ltsviz', 'three.min.js')};
for i = 1:numel(candidates)
    if exist(candidates{i}, 'file')
        js = fileread(candidates{i});
        tag = sprintf('<script>%s</script>', js);
        return;
    end
end
tag = ['<script src="https://cdn.jsdelivr.net/npm/three@0.128.0/build/' ...
    'three.min.js"></script>' ...
    '<!-- Local three.js build not found; using CDN fallback. -->'];
end

function path = userHome()
path = getenv('USERPROFILE');
if isempty(path)
    path = getenv('HOME');
end
end
